Repository trento-project/wanda, pull requests merged in 2022-10, with the labels that each got.

#38 Some needed improvements to make the code runnable on prod environment
  config/runtime.exs
  lib/wanda/catalog.ex
Labels: enhancement

#36 Store execution result on Check execution completion
  lib/wanda/execution/result.ex
  lib/wanda/execution/server.ex
  lib/wanda/results.ex
  priv/repo/seeds.exs
  test/execution/server_test.exs
  test/messaging/mapper_test.exs
  test/results_test.exs
  test/support/factory.ex
Labels: enhancement

#39 Enable single pipe check on credo
  .credo.exs
  lib/wanda/results.ex
  test/results_test.exs
Labels: tech-debt

#40 Serve the execution results through an endpoint
  .formatter.exs
  lib/wanda/results.ex
  lib/wanda/results/execution_result.ex
  lib/wanda_web/api_spec.ex
  lib/wanda_web/controllers/executions_controller.ex
  lib/wanda_web/controllers/results_controller.ex
  lib/wanda_web/router.ex
  lib/wanda_web/schemas/check_execution.ex
  lib/wanda_web/schemas/check_execution_response.ex
  mix.exs
  mix.lock
  test/results_test.exs
  test/wanda_web/controllers/executions_controller_test.exs
Labels: enhancement

#42 Use env values
  lib/wanda/execution.ex
  lib/wanda/execution/behaviour.ex
  lib/wanda/execution/server.ex
  lib/wanda/execution/state.ex
  lib/wanda/policy.ex
  mix.exs
  mix.lock
  test/execution/server_test.exs
  test/messaging/adapters/amqp/consumer_test.exs
  test/policy_test.exs
  test/support/factory.ex
Labels: enhancement

#48 Cleanup execution controller
  lib/wanda_web/controllers/result_controller.ex
  lib/wanda_web/router.ex
  lib/wanda_web/schemas/check_execution_response.ex
  lib/wanda_web/schemas/list_results_response.ex
  lib/wanda_web/schemas/result.ex
  lib/wanda_web/views/execution_view.ex
  lib/wanda_web/views/result_view.ex
  test/wanda_web/controllers/execution_controller_test.exs
  test/wanda_web/controllers/result_controller_test.exs
  test/wanda_web/views/execution_view_test.exs
  test/wanda_web/views/result_view_test.exs
Labels: tech-debt

#46 Add support for values computation based on environment
  lib/wanda/execution/agent_check_result.ex
  lib/wanda/execution/evaluation.ex
  lib/wanda/execution/server.ex
  lib/wanda/execution/value.ex
  priv/catalog/156F64.yaml
  test/catalog_test.exs
  test/execution/evaluation_test.exs
  test/fixtures/catalog/expect_check.yaml
  test/fixtures/catalog/expect_same_check.yaml
  test/fixtures/catalog/warning_severity_check.yaml
Labels: enhancement

#59 Chore: remove unused miss dep
  mix.exs
  mix.lock
Labels: chore

#61 Load checks properly for the execution
  lib/wanda/catalog.ex
  lib/wanda/execution.ex
  lib/wanda/execution/target.ex
  lib/wanda/messaging/adapters/amqp/consumer.ex
  test/catalog_test.exs
  test/execution/target_test.exs
  test/execution_test.exs
  test/support/factory.ex
Labels: bug

#62 Remove restart directive from container definitions
  docker-compose.yaml
Labels: chore
