Repository trento-project/wanda, pull requests merged in 2022-11, with the labels that each got.

#60 Store execution state
  lib/wanda/execution/server.ex
  lib/wanda/results.ex
  lib/wanda/results/execution_result.ex
  lib/wanda_web/schemas/result_response.ex
  lib/wanda_web/views/result_view.ex
  priv/repo/migrations/20220928131105_add_execution_result.exs
  priv/repo/seeds.exs
  test/execution/server_test.exs
  test/results_test.exs
  test/support/factory.ex
  test/wanda_web/views/result_view_test.exs
Labels: enhancement

#66 Refactor executions api
  lib/wanda/results/execution_result.ex
  lib/wanda_web/controllers/execution_controller.ex
  lib/wanda_web/router.ex
  lib/wanda_web/schemas/execution/agent_check_error.ex
  lib/wanda_web/schemas/execution/agent_check_result.ex
  lib/wanda_web/schemas/execution/check_result.ex
  lib/wanda_web/schemas/execution/expectation_evaluation.ex
  lib/wanda_web/schemas/execution/expectation_evaluation_error.ex
  lib/wanda_web/schemas/execution/expectation_result.ex
  lib/wanda_web/schemas/execution/fact.ex
  lib/wanda_web/schemas/execution/value.ex
  lib/wanda_web/schemas/execution_response.ex
  lib/wanda_web/schemas/list_executions_response.ex
  lib/wanda_web/schemas/list_results_response.ex
  lib/wanda_web/schemas/result_response.ex
  lib/wanda_web/views/execution_view.ex
  lib/wanda_web/views/result_view.ex
  test/results_test.exs
  test/wanda_web/controllers/execution_controller_test.exs
  test/wanda_web/controllers/result_controller_test.exs
  test/wanda_web/views/execution_view_test.exs
  test/wanda_web/views/result_view_test.exs
Labels: enhancement, tech-debt

#70 Bump erlang version to 24.3.4
  .tool-versions
Labels: chore

#74 Add cargo to dockerfile and build rustler
  Dockerfile
Labels: enhancement

#72 Add Checks Specification Documentation
  guides/check_definition.schema.json
  guides/expression_language.md
  guides/gatherers.md
  guides/specification.md
Labels: documentation, enhancement

#89 Document systemd gatherer
  guides/gatherers.md
Labels: documentation

#88 Add Documentation for SBD Gatherer
  guides/gatherers.md
Labels: documentation

#93 Ordered Execution list
  lib/wanda/executions.ex
  test/executions_test.exs
Labels: enhancement

#94 Fix protobuf message mapping
  lib/wanda/messaging/mapper.ex
  lib/wanda/policy.ex
  test/messaging/mapper_test.exs
  test/policy_test.exs
Labels: enhancement

#96 Fix flaky evaluation test
  test/executions/evaluation_test.exs
Labels: bug

#101 Init before start
  docker-compose.checks.yaml
Labels: bug

#106 Add targets execution view
  lib/wanda/executions/execution.ex
  lib/wanda_web/schemas/execution/target.ex
  lib/wanda_web/schemas/execution_response.ex
  lib/wanda_web/views/execution_view.ex
  test/support/factory.ex
  test/wanda_web/views/execution_view_test.exs
Labels: enhancement

#108 Add last execution by group
  lib/wanda/executions.ex
  lib/wanda_web/controllers/execution_controller.ex
  lib/wanda_web/router.ex
  test/executions_test.exs
  test/wanda_web/controllers/execution_controller_test.exs
Labels: enhancement
