Repository trento-project/wanda, pull requests merged in 2022-12, with the labels that each got.

#110 Fix get last execution by group id
  lib/wanda/executions.ex
  test/executions_test.exs
Labels: bug

#109 Improve Execution open api doc
  lib/wanda/executions/agent_check_error.ex
  lib/wanda_web/schemas/execution/agent_check_error.ex
  lib/wanda_web/schemas/execution/check_result.ex
  lib/wanda_web/schemas/execution/fact_error.ex
  test/support/factory.ex
  test/wanda_web/controllers/execution_controller_test.exs
Labels: bug

#136 Document cibadmin gatherer
  guides/gatherers.md
Labels: documentation

#137 Add SBD dump gatherer documentation
  guides/gatherers.md
Labels: documentation, enhancement

#141 Add check DA114A: Corosync has at least 2 rings configured
  priv/catalog/DA114A.yaml
Labels: enhancement, check
