Repository trento-project/wanda, pull requests merged in 2023-07, with the labels that each got.

#258 Update contracts usage
  lib/wanda/executions/server.ex
  lib/wanda/messaging/mapper.ex
  mix.exs
  mix.lock
  test/wanda/messaging/mapper_test.exs
  test/wanda/policy_test.exs
Labels: chore

#260 fixes found by checks-checker
  priv/catalog/00081D.yaml
  priv/catalog/0B6DB2.yaml
  priv/catalog/156F64.yaml
  priv/catalog/15F7A8.yaml
  priv/catalog/205AF7.yaml
  priv/catalog/21FCA6.yaml
  priv/catalog/222A57.yaml
  priv/catalog/24ABCB.yaml
  priv/catalog/32CFC6.yaml
  priv/catalog/33403D.yaml
  priv/catalog/373DB8.yaml
  priv/catalog/49591F.yaml
  priv/catalog/53D035.yaml
  priv/catalog/61451E.yaml
  priv/catalog/68626E.yaml
  priv/catalog/6E9B82.yaml
  priv/catalog/790926.yaml
  priv/catalog/7E0221.yaml
  priv/catalog/816815.yaml
  priv/catalog/822E47.yaml
  priv/catalog/845CC9.yaml
  priv/catalog/9FAAD0.yaml
  priv/catalog/9FEFB0.yaml
  priv/catalog/A1244C.yaml
  priv/catalog/B089BE.yaml
  priv/catalog/C3166E.yaml
  priv/catalog/C620DC.yaml
  priv/catalog/CAEFF1.yaml
  priv/catalog/D028B9.yaml
  priv/catalog/D78671.yaml
  priv/catalog/DA114A.yaml
  priv/catalog/DC5429.yaml
  priv/catalog/F50AF5.yaml
  priv/catalog/FB0E0D.yaml
Labels: documentation, check

#259 initial checks for VMware vSphere (jsc#TRNT-1682)
  priv/catalog/00081D.yaml
  priv/catalog/0B6DB2.yaml
  priv/catalog/156F64.yaml
  priv/catalog/15F7A8.yaml
  priv/catalog/205AF7.yaml
  priv/catalog/21FCA6.yaml
  priv/catalog/24ABCB.yaml
  priv/catalog/32CFC6.yaml
  priv/catalog/33403D.yaml
  priv/catalog/373DB8.yaml
  priv/catalog/49591F.yaml
  priv/catalog/53D035.yaml
  priv/catalog/61451E.yaml
  priv/catalog/68626E.yaml
  priv/catalog/6E9B82.yaml
  priv/catalog/790926.yaml
  priv/catalog/7E0221.yaml
  priv/catalog/816815.yaml
  priv/catalog/822E47.yaml
  priv/catalog/845CC9.yaml
  priv/catalog/A1244C.yaml
  priv/catalog/B089BE.yaml
  priv/catalog/C620DC.yaml
  priv/catalog/CAEFF1.yaml
  priv/catalog/D78671.yaml
  priv/catalog/DA114A.yaml
  priv/catalog/FB0E0D.yaml
Labels: documentation, check

#271 Refactor demo server
  README.md
  config/demo.exs
  config/test.exs
  demo/fake_evaluation.ex
  demo/fake_gathered_facts.ex
  demo/fake_server.ex
  guides/development/demo.md
  mix.exs
  priv/demo/fake_facts.yaml
  test/demo/fake_evaluation_test.exs
  test/demo/fake_gathered_facts_test.exs
  test/demo/fake_server_test.exs
  test/fixtures/demo/fake_facts_test.yaml
Labels: enhancement, elixir

#275 Fix formatting in demo guide
  guides/development/demo.md
Labels: bug, documentation
