Repository trento-project/wanda, pull requests merged in 2023-09, with the labels that each got.

#296 Add passwd gatherer documentation
  guides/gatherers.md
Labels: enhancement

#299 Add saptune gatherer documentation
  guides/gatherers.md
Labels: documentation

#298 Add groups gatherer docs
  guides/gatherers.md
Labels: documentation

#301 Add fstab gatherer docs
  guides/gatherers.md
Labels: documentation

#300 Fix cache-miss in CI pipeline
  .github/workflows/ci.yaml
Labels: ci
