Repository trento-project/wanda, pull requests merged in 2023-03, with the labels that each got.

#206 Make cors optional on production
  config/config.exs
  config/dev.exs
  config/runtime.exs
  config/test.exs
  docker-compose.checks.yaml
  lib/wanda_web/auth/jwt_auth_plug.ex
  lib/wanda_web/endpoint.ex
  lib/wanda_web/router.ex
  mix.exs
  mix.lock
  test/wanda_web/auth/jwt_auth_plug_test.exs
Labels: enhancement

#209 Update the hack on wanda guide
  guides/development/hack_on_wanda.md
Labels: documentation

#223 Add dev.local.exs usage
  .gitignore
  config/dev.exs
Labels: chore

#224 Expectation results result to false when some agent evaluation is missing
  lib/wanda/executions/evaluation.ex
  test/wanda/executions/evaluation_test.exs
Labels: bug

#225 Add healthcheck and readiness endpoints
  lib/wanda_web/controllers/health_controller.ex
  lib/wanda_web/router.ex
  lib/wanda_web/schemas/health.ex
  lib/wanda_web/schemas/ready.ex
  lib/wanda_web/views/health_view.ex
  test/wanda_web/controllers/health_test.exs
  test/wanda_web/views/health_view_test.exs
Labels: elixir

#227 Rename `HealthcheckViewTest` -> `HealthViewTest`
  test/wanda_web/views/health_view_test.exs
Labels: tech-debt, elixir

#228 Rename `health_test.exs` -> `health_controller_test.exs`
  test/wanda_web/controllers/health_controller_test.exs
Labels: tech-debt, elixir
