Repository trento-project/wanda, pull requests merged in 2023-08, with the labels that each got.

#277 Prepare for release 1.1.0
  CHANGELOG.md
  mix.exs
Labels: release

#280 Add a pipeline step that checks for APIs changes compatibility
  .github/workflows/ci.yaml
Labels: enhancement, ci

#279 Load fake facts config from proper location
  config/runtime.exs
  demo/fake_gathered_facts.ex
Labels: chore
