Repository trento-project/wanda, pull requests merged in 2023-02, with the labels that each got.

#181 Run CI `test` step on different versions of Elixir & OTP
  .github/workflows/ci.yaml
  .tool-versions
Labels: tech-debt

#182 Update package_version gatherer doc
  guides/gatherers.md
Labels: documentation

#183 Api version v1
  lib/wanda_web/controllers/v1/catalog_controller.ex
  lib/wanda_web/controllers/v1/execution_controller.ex
  lib/wanda_web/plugs/api_redirector.ex
  lib/wanda_web/router.ex
  lib/wanda_web/views/error_view.ex
  lib/wanda_web/views/v1/catalog_view.ex
  lib/wanda_web/views/v1/execution_view.ex
  test/wanda_web/controllers/v1/catalog_controller_test.exs
  test/wanda_web/controllers/v1/execution_controller_test.exs
  test/wanda_web/plugs/api_redirector_test.exs
  test/wanda_web/views/v1/catalog_view_test.exs
  test/wanda_web/views/v1/execution_view_test.exs
Labels: elixir

#124 rewrite trento community checks regarding 'package version'
  priv/catalog/222A57.yaml
  priv/catalog/9FAAD0.yaml
  priv/catalog/9FEFB0.yaml
  priv/catalog/C3166E.yaml
  priv/catalog/CAEFF1.yaml
  priv/catalog/D028B9.yaml
  priv/catalog/DC5429.yaml
  priv/catalog/F50AF5.yaml
Labels: check

#204 Facts schema value lists maps
  lib/wanda_web/schemas/execution/fact.ex
  test/wanda_web/controllers/v1/execution_controller_test.exs
Labels: tech-debt, elixir
