Repository trento-project/wanda, pull requests merged in 2023-01, with the labels that each got.

#155 Document best practices
  guides/specification.md
  priv/catalog/156F64.yaml
  priv/catalog/DA114A.yaml
Labels: documentation

#123 rewrite trento community checks regarding 'sbd' configuration
  priv/catalog/0B6DB2.yaml
  priv/catalog/49591F.yaml
  priv/catalog/61451E.yaml
  priv/catalog/816815.yaml
Labels: check

#142 rewrite trento community checks regarding 'sbd dump' configuration
  priv/catalog/68626E.yaml
  priv/catalog/B089BE.yaml
Labels: check

#146 rewrite trento community checks regarding 'cibadmin' configuration
  priv/catalog/205AF7.yaml
  priv/catalog/373DB8.yaml
Labels: check

#159 Clean up doc saying that expectation evaluation has access to the env
  guides/specification.md
Labels: documentation

#158 Document the trento-agent facts command
  README.md
Labels: documentation

#163 Add premium flag option to catalog loading code
  guides/check_definition.schema.json
  guides/specification.md
  lib/wanda/catalog.ex
  lib/wanda/catalog/check.ex
  lib/wanda_web/schemas/catalog/check.ex
  test/catalog_test.exs
  test/fixtures/catalog/expect_check.yaml
  test/support/factory.ex
Labels: enhancement

#162 Add doc for the new package_version comparisons
  guides/gatherers.md
Labels: documentation

#169 Remove ssh-address flag reference from docs
  README.md
Labels: documentation

#166 Set critical state on agent timeout and warning severity
  lib/wanda/executions/evaluation.ex
  test/executions/evaluation_test.exs
Labels: bug

#170 Chore: move tests in subfolder
  test/wanda/catalog_test.exs
  test/wanda/executions/evaluation_test.exs
  test/wanda/executions/gathering_test.exs
  test/wanda/executions/server_test.exs
  test/wanda/executions/target_test.exs
  test/wanda/executions_test.exs
  test/wanda/messaging/adapters/amqp/consumer_test.exs
  test/wanda/messaging/mapper_test.exs
  test/wanda/policy_test.exs
Labels: chore

#168 Add JWT auth
  config/config.exs
  config/dev.exs
  config/runtime.exs
  config/test.exs
  docker-compose.checks.yaml
  lib/wanda_web/api_spec.ex
  lib/wanda_web/auth/access_token.ex
  lib/wanda_web/auth/jwt_auth_plug.ex
  lib/wanda_web/router.ex
  mix.exs
  mix.lock
  test/test_helper.exs
  test/wanda_web/auth/jwt_auth_plug_test.exs
Labels: enhancement

#172 Fix default value when getting system env for JWT_AUTHENTICATION_ENABLED
  config/runtime.exs
Labels: bug

#171 Execution started event
  lib/wanda/executions/server.ex
  lib/wanda/messaging/mapper.ex
  mix.exs
  mix.lock
  test/wanda/executions/server_test.exs
  test/wanda/messaging/mapper_test.exs
Labels: check

#173 Build in obs
  .github/workflows/ci.yaml
  hack/get_version_from_git.sh
  hack/gh_release_to_obs_changeset.py
  packaging/suse/Dockerfile
  packaging/suse/_constraints
  packaging/suse/_service
Labels: enhancement

#175 Use new `trento-wanda` image name for check development environment
  docker-compose.checks.yaml
Labels: chore

#177 Bump BCI base image to 15.4 for dev Dockerfile
  Dockerfile
Labels: chore

#179 Build wanda with premium checks, if available
  packaging/suse/Dockerfile
Labels: enhancement

#178 Add information on how to install wanda directly for development
  README.md
  guides/development/hack_on_wanda.md
  mix.exs
Labels: documentation
