Repository trento-project/wanda, pull requests merged in 2023-10, with the labels that each got.

#297 Handle gathered fact nil value
  lib/wanda/executions/fact.ex
  lib/wanda/messaging/mapper.ex
  test/wanda/messaging/mapper_test.exs
Labels: bug

#305 Add sap_profiles gatherer documentation
  guides/gatherers.md
Labels: documentation

#307 dir_scan gatherer docs
  guides/gatherers.md
Labels: documentation

#311 Add sapcontrol gatherer documentation
  guides/gatherers.md
Labels: documentation

#312 Update checks definition schema
  guides/check_definition.schema.json
Labels: enhancement, check

#317 Pin all the gatherer version in checks to v1
  priv/catalog/00081D.yaml
  priv/catalog/0B6DB2.yaml
  priv/catalog/156F64.yaml
  priv/catalog/15F7A8.yaml
  priv/catalog/205AF7.yaml
  priv/catalog/21FCA6.yaml
  priv/catalog/222A57.yaml
  priv/catalog/24ABCB.yaml
  priv/catalog/32CFC6.yaml
  priv/catalog/33403D.yaml
  priv/catalog/373DB8.yaml
  priv/catalog/49591F.yaml
  priv/catalog/53D035.yaml
  priv/catalog/61451E.yaml
  priv/catalog/68626E.yaml
  priv/catalog/6E9B82.yaml
  priv/catalog/790926.yaml
  priv/catalog/7E0221.yaml
  priv/catalog/816815.yaml
  priv/catalog/822E47.yaml
  priv/catalog/845CC9.yaml
  priv/catalog/9FAAD0.yaml
  priv/catalog/9FEFB0.yaml
  priv/catalog/A1244C.yaml
  priv/catalog/B089BE.yaml
  priv/catalog/C3166E.yaml
  priv/catalog/C620DC.yaml
  priv/catalog/CAEFF1.yaml
  priv/catalog/D028B9.yaml
  priv/catalog/D78671.yaml
  priv/catalog/DA114A.yaml
  priv/catalog/DC5429.yaml
  priv/catalog/F50AF5.yaml
  priv/catalog/FB0E0D.yaml
Labels: check

#308 Refactor checks from when to metadata
  priv/catalog/00081D.yaml
  priv/catalog/0B6DB2.yaml
  priv/catalog/156F64.yaml
  priv/catalog/15F7A8.yaml
  priv/catalog/205AF7.yaml
  priv/catalog/21FCA6.yaml
  priv/catalog/222A57.yaml
  priv/catalog/24ABCB.yaml
  priv/catalog/32CFC6.yaml
  priv/catalog/33403D.yaml
  priv/catalog/373DB8.yaml
  priv/catalog/49591F.yaml
  priv/catalog/53D035.yaml
  priv/catalog/61451E.yaml
  priv/catalog/68626E.yaml
  priv/catalog/6E9B82.yaml
  priv/catalog/790926.yaml
  priv/catalog/7E0221.yaml
  priv/catalog/816815.yaml
  priv/catalog/822E47.yaml
  priv/catalog/845CC9.yaml
  priv/catalog/9FAAD0.yaml
  priv/catalog/9FEFB0.yaml
  priv/catalog/A1244C.yaml
  priv/catalog/B089BE.yaml
  priv/catalog/C3166E.yaml
  priv/catalog/C620DC.yaml
  priv/catalog/CAEFF1.yaml
  priv/catalog/D028B9.yaml
  priv/catalog/D78671.yaml
  priv/catalog/DA114A.yaml
  priv/catalog/DC5429.yaml
  priv/catalog/F50AF5.yaml
  priv/catalog/FB0E0D.yaml
Labels: enhancement, check

#321 Add metadata documentation
  guides/specification.md
Labels: documentation, enhancement

#324 Add missing metadata reference in Structure section
  guides/specification.md
Labels: documentation, chore

#323 Disp work gatherer docs
  guides/gatherers.md
Labels: documentation

#328 Fix typo in html tag
  guides/gatherers.md
Labels: bug, documentation

#329 Missed versioning changes
  guides/gatherers.md
Labels: bug, documentation

#330 Fix redirection when a query string is involved
  lib/wanda_web/plugs/api_redirector.ex
  test/wanda_web/plugs/api_redirector_test.exs
Labels: bug

#333 Add docs for sapservices gatherer
  guides/gatherers.md
Labels: documentation

#334 Add mount_info gatherer docs
  guides/gatherers.md
Labels: documentation

#337 Port execution view to v2 and cover execution controller with tests
  lib/wanda_web/views/v2/execution_view.ex
  test/wanda_web/controllers/v2/execution_controller_test.exs
  test/wanda_web/views/v2/execution_view_test.exs
Labels: chore
