Repository trento-project/wanda, pull requests merged in 2024-07, with the labels that each got.

#469 Updated metadata of cluster_type with hana_scale_out for existing checks
  priv/catalog/00081D.yaml
  priv/catalog/0B6DB2.yaml
  priv/catalog/156F64.yaml
  priv/catalog/15F7A8.yaml
  priv/catalog/205AF7.yaml
  priv/catalog/21FCA6.yaml
  priv/catalog/222A57.yaml
  priv/catalog/24ABCB.yaml
  priv/catalog/32CFC6.yaml
  priv/catalog/33403D.yaml
  priv/catalog/49591F.yaml
  priv/catalog/53D035.yaml
  priv/catalog/61451E.yaml
  priv/catalog/68626E.yaml
  priv/catalog/790926.yaml
  priv/catalog/7E0221.yaml
  priv/catalog/816815.yaml
  priv/catalog/822E47.yaml
  priv/catalog/845CC9.yaml
  priv/catalog/9FAAD0.yaml
  priv/catalog/9FEFB0.yaml
  priv/catalog/A1244C.yaml
  priv/catalog/B089BE.yaml
  priv/catalog/C3166E.yaml
  priv/catalog/CAEFF1.yaml
  priv/catalog/D028B9.yaml
  priv/catalog/DA114A.yaml
  priv/catalog/DC5429.yaml
  priv/catalog/F50AF5.yaml
  priv/catalog/FB0E0D.yaml
Labels: enhancement

#482 Add architecture type docs
  guides/specification.md
Labels: documentation

#484 Openapi spex objects refactor
  lib/wanda_web/controllers/v1/execution_controller.ex
  lib/wanda_web/controllers/v2/execution_controller.ex
  lib/wanda_web/schemas/accepted_execution_response.ex
  lib/wanda_web/schemas/bad_request.ex
  lib/wanda_web/schemas/health.ex
  lib/wanda_web/schemas/not_found.ex
  lib/wanda_web/schemas/ready.ex
  lib/wanda_web/schemas/v1/catalog/catalog_response.ex
  lib/wanda_web/schemas/v1/catalog/check.ex
  lib/wanda_web/schemas/v1/execution/agent_check_error.ex
  lib/wanda_web/schemas/v1/execution/agent_check_result.ex
  lib/wanda_web/schemas/v1/execution/check_result.ex
  lib/wanda_web/schemas/v1/execution/execution_response.ex
  lib/wanda_web/schemas/v1/execution/expectation_evaluation.ex
  lib/wanda_web/schemas/v1/execution/expectation_evaluation_error.ex
  lib/wanda_web/schemas/v1/execution/expectation_result.ex
  lib/wanda_web/schemas/v1/execution/fact.ex
  lib/wanda_web/schemas/v1/execution/fact_error.ex
  lib/wanda_web/schemas/v1/execution/list_executions_response.ex
  lib/wanda_web/schemas/v1/execution/start_execution_request.ex
  lib/wanda_web/schemas/v1/execution/target.ex
  lib/wanda_web/schemas/v1/execution/value.ex
  lib/wanda_web/schemas/v2/execution/agent_check_result.ex
  lib/wanda_web/schemas/v2/execution/check_result.ex
  lib/wanda_web/schemas/v2/execution/execution_response.ex
  lib/wanda_web/schemas/v2/execution/expectation_evaluation.ex
  lib/wanda_web/schemas/v2/execution/expectation_result.ex
  lib/wanda_web/schemas/v2/execution/list_executions_response.ex
  lib/wanda_web/schemas/v2/execution/start_execution_request.ex
  lib/wanda_web/schemas/v3/catalog/catalog_response.ex
  lib/wanda_web/schemas/v3/catalog/check.ex
  mix.exs
  mix.lock
Labels: tech-debt, elixir

#475 Adapted the existing checks to work with ascs_ers cluster
  priv/catalog/6E9B82.yaml
  priv/catalog/C620DC.yaml
  priv/catalog/D78671.yaml
Labels: enhancement
