Repository trento-project/wanda, pull requests merged in 2024-02, with the labels that each got.

#366 Restore API versioning check in CI
  .github/workflows/ci.yaml
Labels: chore, ci

#364 Rpm package
  .github/workflows/ci.yaml
  packaging/suse/container/Dockerfile
  packaging/suse/container/_constraints
  packaging/suse/container/_service
  packaging/suse/rpm/_service
  packaging/suse/rpm/systemd/trento-wanda.example
  packaging/suse/rpm/systemd/trento-wanda.service
  packaging/suse/rpm/trento-wanda.spec
Labels: github_actions, ci

#367 Update license year to 2024
  README.md
Labels: documentation, chore

#368 Remove leftover start execution schema
  lib/wanda_web/schemas/execution/start_execution_request.ex
Labels: removal

#370 Add unknown expect type in openapi schemas
  lib/wanda_web/schemas/catalog/check.ex
  lib/wanda_web/schemas/execution/expectation_evaluation.ex
  lib/wanda_web/schemas/execution/expectation_result.ex
Labels: chore, breakingchange

#369 Non boolean expectation - expect_enum
  lib/wanda/catalog/expectation.ex
  lib/wanda/executions/evaluation.ex
  lib/wanda/executions/expectation_evaluation.ex
  lib/wanda/executions/expectation_result.ex
  test/support/factory.ex
  test/wanda/executions/evaluation_test.exs
Labels: enhancement

#372 Add expect_enum documentation
  guides/specification.md
Labels: documentation

#374 Add expect_enum to check definition schema
  guides/check_definition.schema.json
Labels: documentation
