Repository trento-project/wanda, pull requests merged in 2024-03, with the labels that each got.

#373 Update execution endpoint schemas to include `expect_enum` expectation
  lib/wanda_web/controllers/v1/execution_controller.ex
  lib/wanda_web/controllers/v2/execution_controller.ex
  lib/wanda_web/router.ex
  lib/wanda_web/schemas/v1/execution/agent_check_error.ex
  lib/wanda_web/schemas/v1/execution/agent_check_result.ex
  lib/wanda_web/schemas/v1/execution/check_result.ex
  lib/wanda_web/schemas/v1/execution/execution_response.ex
  lib/wanda_web/schemas/v1/execution/expectation_evaluation.ex
  lib/wanda_web/schemas/v1/execution/expectation_evaluation_error.ex
  lib/wanda_web/schemas/v1/execution/expectation_result.ex
  lib/wanda_web/schemas/v1/execution/fact.ex
  lib/wanda_web/schemas/v1/execution/fact_error.ex
  lib/wanda_web/schemas/v1/execution/list_executions_response.ex
  lib/wanda_web/schemas/v1/execution/start_execution_request.ex
  lib/wanda_web/schemas/v1/execution/target.ex
  lib/wanda_web/schemas/v1/execution/value.ex
  lib/wanda_web/schemas/v2/execution/agent_check_result.ex
  lib/wanda_web/schemas/v2/execution/check_result.ex
  lib/wanda_web/schemas/v2/execution/execution_response.ex
  lib/wanda_web/schemas/v2/execution/expectation_evaluation.ex
  lib/wanda_web/schemas/v2/execution/expectation_result.ex
  lib/wanda_web/schemas/v2/execution/list_executions_response.ex
  lib/wanda_web/schemas/v2/execution/start_execution_request.ex
  lib/wanda_web/views/v1/execution_view.ex
  lib/wanda_web/views/v2/execution_view.ex
  test/wanda_web/controllers/v2/execution_controller_test.exs
  test/wanda_web/views/v1/execution_view_test.exs
  test/wanda_web/views/v2/execution_view_test.exs
Labels: documentation, enhancement

#376 Add V3 backward compatibility check in CI
  .github/workflows/ci.yaml
Labels: chore, ci

#377 Fix api audience of access token
  lib/wanda_web/auth/access_token.ex
  test/wanda_web/auth/jwt_auth_plug_test.exs
Labels: elixir

#384 Add ascsers_cluster gatherer docs
  guides/gatherers.md
Labels: documentation

#383 Openapi no additional properties take two
  lib/wanda_web/schemas/accepted_execution_response.ex
  lib/wanda_web/schemas/bad_request.ex
  lib/wanda_web/schemas/health.ex
  lib/wanda_web/schemas/not_found.ex
  lib/wanda_web/schemas/ready.ex
  lib/wanda_web/schemas/v1/catalog/catalog_response.ex
  lib/wanda_web/schemas/v1/catalog/check.ex
  lib/wanda_web/schemas/v1/execution/agent_check_error.ex
  lib/wanda_web/schemas/v1/execution/check_result.ex
  lib/wanda_web/schemas/v1/execution/execution_response.ex
  lib/wanda_web/schemas/v1/execution/expectation_evaluation.ex
  lib/wanda_web/schemas/v1/execution/expectation_evaluation_error.ex
  lib/wanda_web/schemas/v1/execution/expectation_result.ex
  lib/wanda_web/schemas/v1/execution/fact.ex
  lib/wanda_web/schemas/v1/execution/fact_error.ex
  lib/wanda_web/schemas/v1/execution/list_executions_response.ex
  lib/wanda_web/schemas/v1/execution/start_execution_request.ex
  lib/wanda_web/schemas/v1/execution/target.ex
  lib/wanda_web/schemas/v1/execution/value.ex
  lib/wanda_web/schemas/v2/execution/agent_check_result.ex
  lib/wanda_web/schemas/v2/execution/check_result.ex
  lib/wanda_web/schemas/v2/execution/execution_response.ex
  lib/wanda_web/schemas/v2/execution/expectation_evaluation.ex
  lib/wanda_web/schemas/v2/execution/expectation_result.ex
  lib/wanda_web/schemas/v2/execution/list_executions_response.ex
  lib/wanda_web/schemas/v2/execution/start_execution_request.ex
  lib/wanda_web/schemas/v3/catalog/catalog_response.ex
  lib/wanda_web/schemas/v3/catalog/check.ex
  lib/wanda_web/views/v1/catalog_view.ex
  test/support/factory.ex
  test/wanda/executions/evaluation_test.exs
  test/wanda_web/views/v1/catalog_view_test.exs
  test/wanda_web/views/v2/catalog_view_test.exs
Labels: tech-debt, elixir
