Repository trento-project/wanda, pull requests merged in 2024-10, with the labels that each got.

#513 Migrate Wanda to Phoenix 1.7 and Remove Phoenix.View
  config/config.exs
  lib/wanda_web.ex
  lib/wanda_web/controllers/fallback_controller.ex
  lib/wanda_web/controllers/health_controller.ex
  lib/wanda_web/endpoint.ex
  lib/wanda_web/plugs/api_redirector.ex
  lib/wanda_web/views/error_json.ex
  lib/wanda_web/views/health_json.ex
  lib/wanda_web/views/health_view.ex
  lib/wanda_web/views/v1/catalog_json.ex
  lib/wanda_web/views/v1/execution_json.ex
  lib/wanda_web/views/v2/catalog_json.ex
  lib/wanda_web/views/v2/catalog_view.ex
  lib/wanda_web/views/v2/execution_json.ex
  lib/wanda_web/views/v3/catalog_json.ex
  lib/wanda_web/views/v3/catalog_view.ex
  test/support/conn_case.ex
  test/wanda_web/views/error_view_json_test.exs
  test/wanda_web/views/health_view_json_test.exs
  test/wanda_web/views/health_view_test.exs
  test/wanda_web/views/v1/catalog_view_json_test.exs
  test/wanda_web/views/v1/execution_view_json_test.exs
  test/wanda_web/views/v2/catalog_view_json_test.exs
  test/wanda_web/views/v2/execution_view_json_test.exs
  test/wanda_web/views/v3/catalog_view_json_test.exs
  test/wanda_web/views/v3/catalog_view_test.exs
Labels: tech-debt, elixir, dependencies

#520 Remove view directory from lib/wanda_web
  lib/wanda_web/controllers/error_helpers.ex
  lib/wanda_web/controllers/error_json.ex
  lib/wanda_web/controllers/health_json.ex
  lib/wanda_web/controllers/v1/catalog_json.ex
  lib/wanda_web/controllers/v1/execution_json.ex
  lib/wanda_web/controllers/v2/catalog_json.ex
  lib/wanda_web/controllers/v2/execution_json.ex
  lib/wanda_web/controllers/v3/catalog_json.ex
Labels: tech-debt

#521 Add ensa_version and filesystem_type env docs
  guides/specification.md
Labels: documentation

#523 Require trento-checks and remove premium source
  packaging/suse/container/Dockerfile
  packaging/suse/rpm/trento-wanda.spec
Labels: enhancement
