Repository trento-project/wanda, pull requests merged in 2025-03, with the labels that each got.

#584 Using custom values in checks executions
  demo/fake_server.ex
  lib/wanda/catalog.ex
  lib/wanda/catalog/customized_value.ex
  lib/wanda/catalog/selected_check.ex
  lib/wanda/executions/check_result.ex
  lib/wanda/executions/evaluation.ex
  lib/wanda/executions/server.ex
  lib/wanda/executions/state.ex
  lib/wanda/executions/value.ex
  lib/wanda_web/schemas/v1/execution/agent_check_result.ex
  lib/wanda_web/schemas/v1/execution/check_result.ex
  lib/wanda_web/schemas/v1/execution/value.ex
  lib/wanda_web/schemas/v2/execution/check_result.ex
  test/support/factory.ex
  test/wanda/catalog/selected_check_test.exs
  test/wanda/catalog_test.exs
  test/wanda/executions/evaluation_test.exs
  test/wanda/executions/server_test.exs
Labels: enhancement

#585 Upgrade github actions runner ubuntu version
  .github/workflows/ci.yaml
Labels: ci

#586 Rabbitmq explicit ssl support
  config/dev.exs
  config/test.exs
  container_fixtures/rabbitmq/certs/ca_certificate.pem
  container_fixtures/rabbitmq/certs/ca_key.pem
  container_fixtures/rabbitmq/certs/client_wanda.trento.local_certificate.pem
  container_fixtures/rabbitmq/certs/client_wanda.trento.local_key.pem
  container_fixtures/rabbitmq/certs/server_rabbit.trento.local_certificate.pem
  container_fixtures/rabbitmq/certs/server_rabbit.trento.local_key.pem
  container_fixtures/rabbitmq/rabbitmq.conf
  docker-compose.yaml
Labels: enhancement

#590 Add boolean to accepted value types
  guides/check_definition.schema.json
Labels: enhancement

#592 Expose resolved original values
  lib/wanda/catalog.ex
  lib/wanda/catalog/evaluation.ex
  lib/wanda/catalog/resolved_value.ex
  lib/wanda/catalog/selectable_check.ex
  lib/wanda/executions/evaluation.ex
  lib/wanda/executions/value.ex
  lib/wanda_web/schemas/v1/checks_selection/customized_check_value.ex
  lib/wanda_web/schemas/v1/checks_selection/not_customized_check_value.ex
  test/fixtures/non_scalar_values_catalog/mixed_values_customizability.yaml
  test/wanda/catalog/evaluation_test.exs
  test/wanda/catalog_test.exs
  test/wanda_web/controllers/v1/catalog_controller_test.exs
Labels: enhancement

#593 Bump rust toolchain
  .github/workflows/ci.yaml
Labels: chore, ci

#595 Send operator execution request to agents
  lib/wanda/messaging.ex
  lib/wanda/messaging/adapters/amqp.ex
  lib/wanda/messaging/adapters/behaviour.ex
  lib/wanda/messaging/mapper.ex
  lib/wanda/operations/catalog/step.ex
  lib/wanda/operations/server.ex
  mix.exs
  mix.lock
  test/demo/fake_server_test.exs
  test/support/messaging/adapters/stub.ex
  test/wanda/executions/server_test.exs
  test/wanda/messaging/mapper_test.exs
  test/wanda/operations/server_test.exs
Labels: enhancement

#599 Receive operator execution reports
  lib/wanda/messaging/mapper.ex
  lib/wanda/operations/agent_report.ex
  lib/wanda/operations/enums/operator_phase.ex
  lib/wanda/operations/operation.ex
  lib/wanda/operations/operator_error.ex
  lib/wanda/operations/operator_result.ex
  lib/wanda/operations/server.ex
  lib/wanda/policy.ex
  lib/wanda_web/controllers/v1/operation_json.ex
  lib/wanda_web/schemas/v1/operation/agent_report.ex
  test/support/factory.ex
  test/wanda/messaging/mapper_test.exs
  test/wanda/operations/server_test.exs
  test/wanda/operations_test.exs
  test/wanda/policy_test.exs
  test/wanda_web/controllers/v1/operation_json_test.exs
Labels: enhancement
