Repository trento-project/wanda, pull requests merged in 2025-05, with the labels that each got.

#608 Add saptune change solution operation to the catalog
  lib/wanda/operations/catalog/registry.ex
  lib/wanda/operations/catalog/saptunechangesolution_v1.ex
Labels: enhancement

#612 Add CODEOWNERS
  .github/CODEOWNERS
  .github/dependabot.yaml
Labels: enhancement

#611 Update CI
  .github/release_drafter.yaml
  .github/workflows/ci.yaml
  .github/workflows/deps.yaml
  .github/workflows/obs.yaml
  .github/workflows/release.yaml
  Dockerfile
  VERSION
  mix.exs
Labels: github_actions, ci

#615 Fix deps cache key in CI
  .github/workflows/ci.yaml
Labels: ci
