Repository trento-project/wanda, pull requests merged in 2025-01, with the labels that each got.

#542 Add hexadecimal value hint to id section
  guides/specification.md
Labels: documentation

#544 Update dockerfiles to use correct elixir/erlang versions
  Dockerfile
  packaging/suse/container/Dockerfile
Labels: chore

#543 Operations orchestration skeleton
  config/dev.exs
  lib/wanda/application.ex
  lib/wanda/operations.ex
  lib/wanda/operations/agent_report.ex
  lib/wanda/operations/catalog/operation.ex
  lib/wanda/operations/catalog/step.ex
  lib/wanda/operations/operation_target.ex
  lib/wanda/operations/server.ex
  lib/wanda/operations/server_behaviour.ex
  lib/wanda/operations/state.ex
  lib/wanda/operations/step_report.ex
  test/support/factory.ex
  test/wanda/operations/server_test.exs
Labels: enhancement

#548 Create and use enum modules
  lib/wanda/catalog.ex
  lib/wanda/catalog/check.ex
  lib/wanda/catalog/enums/expect_type.ex
  lib/wanda/catalog/enums/severity.ex
  lib/wanda/catalog/expectation.ex
  lib/wanda/executions.ex
  lib/wanda/executions/check_result.ex
  lib/wanda/executions/enums/result.ex
  lib/wanda/executions/enums/status.ex
  lib/wanda/executions/evaluation.ex
  lib/wanda/executions/execution.ex
  lib/wanda/executions/expectation_evaluation.ex
  lib/wanda/executions/expectation_result.ex
  lib/wanda/executions/result.ex
  lib/wanda/operations/agent_report.ex
  lib/wanda/operations/enums/result.ex
  lib/wanda/operations/server.ex
  lib/wanda/operations/server_behaviour.ex
  lib/wanda/support/enum.ex
Labels: enhancement, chore

#547 Save operations in the database
  lib/wanda/operations.ex
  lib/wanda/operations/agent_report.ex
  lib/wanda/operations/enums/result.ex
  lib/wanda/operations/enums/status.ex
  lib/wanda/operations/operation.ex
  lib/wanda/operations/server.ex
  lib/wanda/operations/step_report.ex
  priv/repo/migrations/20250109154813_add_operation.exs
  priv/repo/migrations/20250116095113_add_operation_jsonb_indexes.exs
  test/support/factory.ex
  test/wanda/operations/server_test.exs
  test/wanda/operations_test.exs
Labels: enhancement

#550 Add customizable key to disable checks customization for certain checks
  guides/check_definition.schema.json
  guides/specification.md
Labels: documentation, enhancement

#553 Move json view tests to correct folder
  test/wanda_web/controllers/error_json_test.exs
  test/wanda_web/controllers/health_json_test.exs
  test/wanda_web/controllers/v1/catalog_json_test.exs
  test/wanda_web/controllers/v1/execution_json_test.exs
  test/wanda_web/controllers/v2/catalog_json_test.exs
  test/wanda_web/controllers/v2/execution_json_test.exs
  test/wanda_web/controllers/v3/catalog_json_test.exs
Labels: chore

#555 Update gen_rmq to cdimonaco/gen_rmq version 5
  mix.exs
  mix.lock
Labels: dependencies

#552 Extract abilities from token so they can be matched for authorization
  config/config.exs
  lib/wanda/support/abilities_helper.ex
  lib/wanda/users/user.ex
  lib/wanda_web/auth/jwt_auth_plug.ex
  lib/wanda_web/auth/user_detector.ex
  lib/wanda_web/controllers/error_json.ex
  lib/wanda_web/controllers/fallback_controller.ex
  mix.exs
  mix.lock
  test/support/factory.ex
  test/wanda/support/abilities_helper_test.exs
  test/wanda_web/auth/jwt_auth_plug_test.exs
  test/wanda_web/auth/user_detector_test.exs
  test/wanda_web/controllers/error_json_test.exs
  test/wanda_web/controllers/fallback_controller_test.exs
Labels: enhancement

#549 Operations registry
  lib/wanda/operations/catalog/operation.ex
  lib/wanda/operations/catalog/registry.ex
  lib/wanda/operations/catalog/saptuneapplysolution_v1.ex
  lib/wanda/operations/catalog/step.ex
  test/wanda/operations/catalog/registry_test.exs
Labels: enhancement

#551 Operations timeout
  lib/wanda/operations/catalog/step.ex
  lib/wanda/operations/enums/result.ex
  lib/wanda/operations/server.ex
  lib/wanda/operations/server_behaviour.ex
  lib/wanda/operations/state.ex
  test/support/factory.ex
  test/wanda/operations/server_test.exs
Labels: enhancement

#554 Operations controller
  config/config.exs
  config/prod.exs
  lib/wanda/operations.ex
  lib/wanda_web/controllers/v1/operation_controller.ex
  lib/wanda_web/controllers/v1/operation_json.ex
  lib/wanda_web/router.ex
  lib/wanda_web/schemas/v1/operation/agent_report.ex
  lib/wanda_web/schemas/v1/operation/list_operations_response.ex
  lib/wanda_web/schemas/v1/operation/operation_response.ex
  lib/wanda_web/schemas/v1/operation/operation_target.ex
  lib/wanda_web/schemas/v1/operation/step_report.ex
  test/wanda/operations_test.exs
  test/wanda_web/controllers/v1/operation_controller_test.exs
  test/wanda_web/controllers/v1/operation_json_test.exs
Labels: enhancement

#560 Refactor check loading
  config/test.exs
  lib/wanda/catalog.ex
  test/support/catalog_case.ex
  test/wanda/catalog_test.exs
  test/wanda_web/controllers/v1/catalog_controller_test.exs
  test/wanda_web/controllers/v2/catalog_controller_test.exs
  test/wanda_web/controllers/v3/catalog_controller_test.exs
Labels: enhancement

#559 Enrich catalog operation data
  lib/wanda/operations.ex
  lib/wanda/operations/catalog/operation.ex
  lib/wanda/operations/catalog/registry.ex
  lib/wanda/operations/catalog/step.ex
  lib/wanda/operations/operation.ex
  lib/wanda/operations/server.ex
  lib/wanda_web/controllers/v1/operation_controller.ex
  lib/wanda_web/controllers/v1/operation_json.ex
  lib/wanda_web/schemas/v1/operation/operation_response.ex
  lib/wanda_web/schemas/v1/operation/step_report.ex
  priv/repo/migrations/20250123143407_add_catalog_operation_id_to_operation.exs
  test/support/factory.ex
  test/support/operations/test_registry.ex
  test/wanda/operations/catalog/registry_test.exs
  test/wanda/operations/server_test.exs
  test/wanda/operations_test.exs
  test/wanda_web/controllers/v1/operation_controller_test.exs
  test/wanda_web/controllers/v1/operation_json_test.exs
Labels: enhancement
