Repository trento-project/wanda, pull requests merged in 2025-02, with the labels that each got.

#564 Retrieve customizations for a specific execution group
  lib/wanda/catalog/check_customization.ex
  lib/wanda/checks_customizations.ex
  lib/wanda/support/ecto/json.ex
  test/wanda/checks_customizations_test.exs
Labels: enhancement

#566 Add customization auth policy
  lib/wanda/catalog/check_customization.ex
  lib/wanda/catalog/customization_policy.ex
  lib/wanda_web/controllers/v1/checks_customizations_controller.ex
  test/support/user_aware_conn_case.ex
  test/wanda/catalog/customization_policy_test.exs
  test/wanda_web/controllers/v1/checks_customization_controller_test.exs
Labels: enhancement

#562 Set operation as aborted
  lib/wanda/operations.ex
  lib/wanda/operations/enums/status.ex
  lib/wanda/operations/server.ex
  lib/wanda/operations/state.ex
  lib/wanda_web/controllers/v1/operation_controller.ex
  test/wanda/operations/server_test.exs
  test/wanda/operations_test.exs
Labels: enhancement

#571 Adjust doc
  README.md
Labels: documentation

#572 Reset check customization
  lib/wanda/catalog/customization_policy.ex
  lib/wanda/checks_customizations.ex
  lib/wanda_web/controllers/fallback_controller.ex
  lib/wanda_web/controllers/v1/checks_customizations_controller.ex
  lib/wanda_web/router.ex
  test/wanda/catalog/customization_policy_test.exs
  test/wanda/checks_customizations_test.exs
  test/wanda_web/controllers/fallback_controller_test.exs
  test/wanda_web/controllers/v1/checks_customization_controller_test.exs
Labels: enhancement

#573 Improve api routes
  lib/wanda_web/router.ex
  test/wanda_web/controllers/v1/catalog_controller_test.exs
  test/wanda_web/controllers/v1/checks_customization_controller_test.exs
Labels: enhancement

#582 Bump trento contracts to 0.2.0
  mix.exs
  mix.lock
Labels: dependencies
